# Examples: Converting HEC-RAS HDF datasets to xarrays

In [1]:
import xarray as xr
import h5py
import numpy as np

## Attributes function

In [2]:
def create_attributes_dict(dataset):
    attrs = {}
    for key, value in dataset.attrs.items():
        # print('type(value) = ', type(value))
        if type(value) == np.bytes_:
            attrs[key] = value.decode('ascii')
        elif type(value) == np.ndarray:
            values = []
            for v in value:
                if type(v) == np.bytes_:
                    values.append(v.decode('ascii'))
                else:
                    values.append(v)
            attrs[key] = values
        else:
            attrs[key] = value
    return attrs

## Water Surface Elevation

In [3]:
with h5py.File('../tests/input_files/Muncie.p04.hdf') as infile:
    water_surface_elev_dataset = infile['Results/Unsteady/Output/Output Blocks/Base Output/Unsteady Time Series/2D Flow Areas/2D Interior Area/Water Surface']
    water_surface_elev_arr = water_surface_elev_dataset[()]
    attrs = create_attributes_dict(water_surface_elev_dataset)
    
x_water_surface_elev = xr.DataArray(water_surface_elev_arr, coords = {'Time': list(range(289)), 'Cells': list(range(5765))}, dims = ('Time', 'Cells'), attrs = attrs)
x_water_surface_elev

<xarray.DataArray (Time: 289, Cells: 5765)>
array([[940.15625, 939.42847, 939.09125, ..., 948.625  , 946.     ,
        950.7133 ],
       [940.15625, 939.42847, 939.09125, ..., 948.625  , 946.     ,
        950.7133 ],
       [940.15625, 939.42847, 939.09125, ..., 948.625  , 946.     ,
        950.7133 ],
       ...,
       [945.2012 , 945.2012 , 945.2012 , ..., 948.625  , 947.05914,
        950.7133 ],
       [945.1997 , 945.1997 , 945.1997 , ..., 948.625  , 947.05194,
        950.7133 ],
       [945.19824, 945.19824, 945.19824, ..., 948.625  , 947.04474,
        950.7133 ]], dtype=float32)
Coordinates:
  * Time     (Time) int64 0 1 2 3 4 5 6 7 8 ... 281 282 283 284 285 286 287 288
  * Cells    (Cells) int64 0 1 2 3 4 5 6 ... 5758 5759 5760 5761 5762 5763 5764
Attributes:
    Can Plot:                   True
    Columns:                    Cells
    Coverage:                   Wet
    Location:                   Cells
    Maximum Value of Data Set:  953.8399
    Minimum Value of Data Set:  924.99866
    Name:                       Water Surface
    Orientation:                Scalar
    Rows:                       Times
    Units:                      ft

## Cell Volume Info

In [4]:
with h5py.File('../tests/input_files/Muncie.p04.hdf') as infile:
    cells_volume_info_dataset = infile['Geometry/2D Flow Areas/2D Interior Area/Cells Volume Elevation Info']
    cells_volume_info_arr = cells_volume_info_dataset[()]
    attrs = create_attributes_dict(cells_volume_info_dataset)

x_cells_volume_info = xr.DataArray(cells_volume_info_arr, dims = ['Index', 'Count'], attrs = attrs)
x_cells_volume_info

<xarray.DataArray (Index: 5765, Count: 2)>
array([[    0,     5],
       [    5,     9],
       [   14,    12],
       ...,
       [37912,     0],
       [37912,     0],
       [37912,     0]], dtype=int32)
Dimensions without coordinates: Index, Count
Attributes:
    Column:   ['Starting Index', 'Count']
    Row:      Cell

## Cell Elevation-Volume Table

In [5]:
with h5py.File('../tests/input_files/Muncie.p04.hdf') as infile:
    cells_elev_vol_dataset = infile['Geometry/2D Flow Areas/2D Interior Area/Cells Volume Elevation Values']
    cells_elev_vol_arr = cells_elev_vol_dataset[()]
    attrs = create_attributes_dict(cells_elev_vol_dataset)

x_cells_elev_vol = xr.DataArray(cells_elev_vol_arr, dims = ('Elevation', 'Volume'), attrs = attrs)
x_cells_elev_vol


<xarray.DataArray (Elevation: 37912, Volume: 2)>
array([[940.15625  ,   0.       ],
       [940.2344   ,   6.0492353],
       [940.32104  ,  16.361727 ],
       ...,
       [945.0296   , 213.54762  ],
       [945.22565  , 440.82742  ],
       [945.37036  , 636.75256  ]], dtype=float32)
Dimensions without coordinates: Elevation, Volume
Attributes:
    Column:   ['Elevation', 'Volume']
    Row:      row

## Cell Surface Area

In [6]:
with h5py.File('../tests/input_files/Muncie.p04.hdf') as infile:
    cells_surface_area_dataset = infile['Geometry/2D Flow Areas/2D Interior Area/Cells Surface Area']
    cells_surface_area_arr = cells_surface_area_dataset[()]
    attrs = create_attributes_dict(cells_surface_area_dataset)

x_cells_surface_area = xr.DataArray(cells_surface_area_arr, dims = ('Cells'), coords = {'Cells': list(range(5765))}, attrs = attrs)
x_cells_surface_area

<xarray.DataArray (Cells: 5765)>
array([2478.019 , 2094.556 , 2259.9414, ...,    0.    ,    0.    ,
          0.    ], dtype=float32)
Coordinates:
  * Cells    (Cells) int64 0 1 2 3 4 5 6 ... 5758 5759 5760 5761 5762 5763 5764
Attributes:
    Column:   ['Surface Area']
    Row:      Cell